wsgi/healthmeter/hmeter_frontend/urls.py
# Copyright 2017 Red Hat, Inc.
# License: GPLv3 or any later version

from django.conf.urls import include, url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView, TemplateView

from . import views

project_urlpatterns = [
    url(r'^$', views.project.ProjectIndex.as_view(), name="index"),

    url(r'^\+problems$', views.project.ProblematicProjects.as_view(),
        name="problems"),

    url(r'^\+compare/(?P<ids>([0-9]+,)+[0-9]+)$',
        views.project.CompareProject.as_view(),
        name="compare"),

    url(r'^(?P<pk>\d+)/$', views.project.ProjectDetail.as_view(),
        name="detail"),

    url(r'^(?P<id>\d+)/commits/(?P<domain>.*)$',
        views.project.CommitDataView.as_view(),
        name="commitdata"),

    url(r'^(?P<id>\d+)/committers/(?P<domain>.*)$',
        views.project.CommitterDataView.as_view(),
        name="committerdata"),

    url(r'^(?P<id>\d+)/emails/(?P<domain>.*)$',
        views.project.MailingListDataView.as_view(),
        name="mldata"),

    url(r'^(?P<id>\d+)/emailers/(?P<domain>.*)$',
        views.project.MailingListPosterDataView.as_view(),
        name="mlposterdata"),

    url(r'^(?P<id>\d+)/bugs/(?P<domain>.*)$',
        views.project.BugDataView.as_view(),
        name="btdata"),

    url(r'^(?P<id>\d+)/bugreporters/(?P<domain>.*)$',
        views.project.BugReporterDataView.as_view(),
        name="btreporterdata"),

    url(r'^(?P<id>\d+)/blogs/$', views.project.BlogDataView.as_view(),
        name="blogdata"),

    url(r'^(?P<id>\d+)/events/$', views.project.EventDataView.as_view(),
        name="eventdata"),

    url(r'(?P<id>\d+)/metric/$', views.project.MetricDataView.as_view(),
        name="metricdata"),

    url(r'(?P<pk>\d+)/metrichistory/$',
        views.project.MetricHistoryView.as_view(),
        name="metrichistory"),
]

urlpatterns = [
    url(r'^$',
        RedirectView.as_view(
            url=reverse_lazy('hmeter_frontend:project:index'),
            permanent=True
        )),

    url(r'^about$', views.static.About.as_view(),
        name='about'),

    url(r'^contact$', views.static.Contact.as_view(),
        name='contact'),

    url(r'^feedback$', views.feedback.FeedbackView.as_view(),
        name='feedback'),

    url(r'^project/', include(project_urlpatterns,
                              namespace='project')),

    url(r'^business-units/', views.business_units.BusinessUnitIndex.as_view(),
        name='business_units'),

    url(r'^all-projects/', views.all_projects.AllProjectsView.as_view(),
        name='all_projects'),
]

wsgi/healthmeter/urls.py
# Copyright 2017 Red Hat, Inc.
# License: GPLv3 or any later version

from django.conf.urls import include, url, static
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

import django_js_reverse.views

import healthmeter.hmeter_frontend.urls
from healthmeter.views.errors import PageNotFoundView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^jsreverse/', django_js_reverse.views.urls_js,
        name='js_reverse'),
]

if settings.DEBUG:
    urlpatterns += static.static(settings.MEDIA_URL,
                                 document_root=settings.MEDIA_ROOT)

urlpatterns += [
    url(r'', include(healthmeter.hmeter_frontend.urls,
                     namespace="hmeter_frontend")),
]

handler404 = PageNotFoundView.as_view()

wsgi/healthmeter/hmeter_frontend/models.py
# Copyright 2017 Red Hat, Inc.
# License: GPLv3 or any later version

import colorful.fields
import datetime
from django.core.exceptions import ValidationError, MultipleObjectsReturned
from django.core.cache import cache
from django.core.urlresolvers import reverse
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey, TreeManyToManyField
from mptt.managers import TreeManager

from jsonfield.fields import JSONField

import hashlib
import itertools
import json
import logging

from healthmeter.participantinfo.models import *
from healthmeter.projectinfo import models as projectmodels
from healthmeter.vcsinfo import models as vcsmodels
from healthmeter.mlinfo import models as mlmodels
from healthmeter.btinfo import models as btmodels
from healthmeter.eventinfo import models as eventmodels
from healthmeter.bloginfo import models as blogmodels

from healthmeter.managers import (ProxyTreeManager, QuerySetManager,
                                  get_natural_key_manager)

from healthmeter.utils import djcached
from .utils.cache import cached_property, djcached_by_project
from .utils.containers import AttrDict
from .utils.stats import max_or_none
from .managers import ProjectQuerySet, ProjectManager
from .metrics.constants import score_to_colour


logger = logging.getLogger(__name__)


class Project(projectmodels.Project):
    objects = ProjectManager()
    QuerySet = ProjectQuerySet

    class Meta(projectmodels.Project.Meta):
        proxy = True

    def get_absolute_url(self):
        return reverse('hmeter_frontend:project:detail',
                       kwargs={'pk': self.id})

    @property
    def all_projects(self):
        return self.get_descendants(include_self=True)

    @property
    def all_releases(self):
        return projectmodels.Release.objects.filter(
            project__in=self.all_projects)

    @property
    def all_licenses(self):
        return projectmodels.License.objects.filter(
            projects__in=self.all_projects).distinct('id')

    @property
    def all_bug_trackers(self):
        return btmodels.BugNamespace.objects.filter(
            projects__in=self.all_projects)

    @property
    def all_vcs_repositories(self):
        return vcsmodels.Repository.objects.filter(
            project__in=self.all_projects)

    @property
    def all_mailing_lists(self):
        return mlmodels.MailingList.objects.filter(
            projects__in=self.all_projects)

    @property
    def all_blogs(self):
        return blogmodels.Blog.objects.filter(projects__in=self.all_projects)

    @cached_property
    @djcached_by_project('start_date', 24 * 3600)
    def smart_start_date(self):
        if self.start_date:
            return self.start_date

        try:
            return vcsmodels.Commit \
                .objects \
                .filter(
                    repository__project__in=self.all_projects
                ) \
                .aggregate(start_date=models.Min('timestamp'))['start_date'] \
                .date()
        except (KeyError, AttributeError):
            return None

    @property
    @djcached_by_project('last_updated', 24 * 3600)
    def last_updated(self):
        projects = self.all_projects

        querysets = (self.all_vcs_repositories,
                     self.all_bug_trackers,
                     self.all_mailing_lists,
                     self.all_blogs)

        last_updated_dates = (qs.aggregate(lu=models.Max('last_updated'))['lu']
                              for qs in querysets)
        return max_or_none(last_updated_dates)

    @cached_property
    @djcached_by_project('last_activity', 24 * 3600)
    def last_activity(self):
        projects = self.all_projects

        extra_args = {}

        def update_timestamp(new_timestamp):
            if new_timestamp is None:
                return

            try:
                extra_args['timestamp__gt'] = max(
                    extra_args['timestamp__gt'],
                    new_timestamp)
            except KeyError:
                extra_args['timestamp__gt'] = new_timestamp

        timestamp = vcsmodels.Commit.objects \
            .filter(repository__project__in=projects,
                    **extra_args) \
            .aggregate(timestamp=models.Max('timestamp'))['timestamp']
        update_timestamp(timestamp)

        timestamp = mlmodels.Post.objects \
            .filter(mailing_lists__projects__in=projects,
                    **extra_args) \
            .aggregate(timestamp=models.Max('timestamp'))['timestamp']
        update_timestamp(timestamp)

        timestamp = btmodels.Comment.objects \
            .filter(bug__tracker_info__projects__in=projects,
                    **extra_args) \
            .aggregate(timestamp=models.Max('timestamp'))['timestamp']
        update_timestamp(timestamp)

        timestamp = blogmodels.Post.objects \
            .filter(blog__projects__in=projects, **extra_args) \
            .aggregate(timestamp=models.Max('timestamp'))['timestamp']
        update_timestamp(timestamp)

        most_recent_date = extra_args.get('timestamp__gt', None)

        return most_recent_date

    @property
    def score(self):
        return self.get_score()

    def __gen_score_cache_key(self, start=None, end=None, **kwargs):
        epoch = datetime.datetime.utcfromtimestamp(0)

        def td2epoch(td):
            return td.days * 24 * 3600 + td.seconds

        if start:
            start = int(td2epoch(start - epoch))

        if end:
            end = int(td2epoch(end - epoch))

        return 'project:{0}:health_score:{1}:{2}'.format(self.id, start, end)

    @djcached(__gen_score_cache_key, 24 * 3600)
    def get_score(self, start=None, end=None):
        metric = Metric.objects.root_nodes()[:1][0]
        return metric.get_result(self, start, end)


class EmailDomain(EmailDomain):
    objects = QuerySetManager()

    class Meta:
        proxy = True

    class QuerySet(models.query.QuerySet):
        def with_commit_count(self):
            return self.values('domain') \
                .annotate(commit_count=models.Count('addresses__owner__'
                                                    'committer_ids__'
                                                    'commits__id',
                                                    distinct=True),
                          address_count=models.Count('addresses__id',
                                                     distinct=True)) \
                .order_by('-commit_count')

        def with_mlpost_count(self):
            return self.values('domain') \
                .annotate(mlpost_count=models.Count('addresses__owner__'
                                                    'mailing_list_'
                                                    'posts__id',
                                                    distinct=True),
                          address_count=models.Count('addresses__id',
                                                     distinct=True)) \
                .order_by('-mlpost_count')

        def with_btcomment_count(self):
            return self.values('domain') \
                .annotate(btcomment_count=models.Count('addresses__owner__'
                                                       'bug_comments__id',
                                                       distinct=True),
                          address_count=models.Count('addresses__id',
                                                     distinct=True)) \
                .order_by('-btcomment_count')

        def with_participant_count(self):
            return self.values('domain') \
                .annotate(participant_count=models.Count('addresses__owner__'
                                                         'id', distinct=True),
                          address_count=models.Count('addresses__id',
                                                     distinct=True)) \
                .order_by('-participant_count')


class MetricScoreConstants(models.Model):
    red_score = models.FloatField()
    yellow_score = models.FloatField()
    green_score = models.FloatField()

    ry_boundary = models.FloatField()
    yg_boundary = models.FloatField()

    class Meta:
        verbose_name = "Metric Score Constants"
        verbose_name_plural = "Metric Score Constants instances"

    def clean(self):
        if not (self.red_score <= self.ry_boundary <= self.yellow_score
                <= self.yg_boundary <= self.green_score):
            raise ValidationError("Green score should be highest, followed by "
                                  "yg boundary, yellow score, ry boundary, "
                                  "and red score")

    def save(self, *args, **kwargs):
        self.clean()

        return super(MetricScoreConstants, self).save(*args, **kwargs)

    def __str__(self):
        return '(red=%.2f, ry=%.2f, yellow=%.2f, yg=%.2f, green=%.2f)' % (
            self.red_score,
            self.ry_boundary,
            self.yellow_score,
            self.yg_boundary,
            self.green_score)


class MetricAlgorithm(models.Model):
    name = models.CharField(max_length=50, unique=True)
    desc = models.CharField(max_length=300)

    objects = get_natural_key_manager('name')

    def __str__(self):
        return self.name


class Metric(MPTTModel):
    parent = TreeForeignKey('self', related_name='children',
                            null=True, blank=True)
    weight = models.IntegerField()
    algorithm = models.ForeignKey(MetricAlgorithm, null=True, blank=True)
    title = models.CharField(max_length=300, blank=True)
    description = models.TextField(blank=True)
    template_name = models.CharField(max_length=50, blank=True, default='')
    sibling_order = models.IntegerField(default=0, blank=True)
    colour = colorful.fields.RGBColorField(blank=True)

    time_based = models.BooleanField(default=True)

    class MPTTMeta:

wsgi/healthmeter/hmeter_frontend/forms.py
# Copyright 2017 Red Hat, Inc.
# License: GPLv3 or any later version

from django import forms


class FeedbackForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    subject = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

wsgi/healthmeter/hmeter_frontend/views/business_units.py
# Copyright 2017 Red Hat, Inc.
# License: GPLv3 or any later version

from django.views.generic import TemplateView
import itertools

from healthmeter.utils import ProxyObject
from healthmeter.hmeter_frontend.models import Project, Metric
from healthmeter.projectinfo.models import BusinessUnit


class BusinessUnitIndex(TemplateView):
    template_name = 'hmeter_frontend/business-units.html'

    def get_context_data(self, **kwargs):
        data = super(BusinessUnitIndex, self).get_context_data(**kwargs)
        business_units = BusinessUnit.objects.prefetch_related('products')
        projects = Project.objects.filter(parent__isnull=True) \
                                  .order_by('business_unit') \
                                  .prefetch_dates() \
                                  .with_l1_scores()

        bu_index = dict(
            (buid, list(projs))
            for buid, projs in
            itertools.groupby(projects, lambda p: p.business_unit_id))

        data['descriptions'] = dict((project.id, project.description)
                                    for project in projects)

        def get_products(bu):
            # sort locally because of prefetch
            for product in sorted(bu.products.all(), key=lambda p: p.name):
                if product.name == 'JBoss BRMS':
                    yield ProxyObject(product,
                                      projects=bu_index.get(bu.id, None))
                else:
                    yield product

        data['business_units'] = [
            ProxyObject(bu,
                        root_projects=bu_index.get(bu.id, None),
                        products=get_products(bu))
            for bu in business_units
        ]
        data['unassociated_projects'] = bu_index[None]

        data['l1_metrics'] = Metric.objects.filter(level=1).order_by('lft')

        return data

wsgi/healthmeter/hmeter_frontend/views/feedback.py
# Copyright 2017 Red Hat, Inc.
# License: GPLv3 or any later version

from django.conf import settings
from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseBadRequest
from django.views.generic import View
from django.views.decorators.csrf import csrf_exempt

from healthmeter.views.generic import JsonView
from healthmeter.hmeter_frontend.forms import FeedbackForm
import json


class FeedbackView(View):
    @classmethod
    def as_view(cls, *args, **kwargs):
        return csrf_exempt(super().as_view(*args, **kwargs))

    @staticmethod
    def format_email(name, email):
        return '{0} <{1}>'.format(name, email)

    def post(self, request, *args, **kwargs):
        form = FeedbackForm(request.POST)

        if not form.is_valid():
            respdata = {
                'status': 'fail',
                'errors': form.errors
            }
            responsecls = HttpResponseBadRequest

        else:
            respdata = {
                'status': 'ok',
                'errors': {}
            }
            responsecls = HttpResponse
            recipients = [self.format_email(name, email)
                          for name, email in settings.MANAGERS]

            message = '{0}\n-- \nSent from: {1}\n'.format(
                form.cleaned_data['message'],
                request.META['HTTP_REFERER'])

            send_mail(subject='[OSP feedback] ' + form.cleaned_data['subject'],
                      message=message,
                      from_email=self.format_email(
                          form.cleaned_data['name'],
                          form.cleaned_data['email']),
                      recipient_list=recipients)

        return responsecls(json.dumps(respdata),
                           content_type='application/json')

wsgi/healthmeter/hmeter_frontend/views/static.py
# Copyright 2017 Red Hat, Inc.
# License: GPLv3 or any later version

from django.views.generic import TemplateView


class About(TemplateView):
    template_name = 'hmeter_frontend/about.html'


class Contact(TemplateView):
    template_name = 'hmeter_frontend/contact.html'


class MigrationSchedule(TemplateView):
    template_name = 'hmeter_frontend/migration-schedule.html'

wsgi/healthmeter/hmeter_frontend/templates/hmeter_frontend/about.html
{% extends "hmeter_frontend/base.html" %}
{% load staticfiles %}

{% block title %}Open Source Prospector: About{% endblock %}

{% block css %}
  {{ block.super }}

  <link rel="stylesheet" type="text/css" href="{% static 'css/about.css' %}" />
{% endblock %}

{% block content %}
  <section>
    <h1>About</h1>
    <p>
      Project Open Source Prospector is created by the Red Hat Legal Team.
    </p>
    <p>
      Open Source Prospector is a tool that aggregates data on open source
      projects. It is designed to provide decision makers with the flexibility
      to do quick and detailed analyses that are objectively based and reliable.
    </p>
    <p>
      Project owner: Harish Pillay
      &lt;{{ "hpillay@redhat.com"|urlize }}&gt;<br />

      Project developer: Chow Loong Jin
      &lt;{{ "lchow@redhat.com"|urlize }}&gt;
    </p>
  </section>

  <section>
    <h1>Attributions</h1>

    <p>
      The Open Source Prospector project would not be possible if not for
      numerous other projects. Listed below are some notable dependencies which
      are exceptionally important to the Open Source Prospector.
    </p>

    <dl>
      <dt><a href="http://www.python.org">Python</a></dt>
      <dd>
        <p>
          The programming language in which the Open Source Prospector project
          is written.
        </p>
      </dd>
      <dt><a href="http://www.djangoproject.com">Django</a></dt>
      <dd>
        <p>
          A Python-based web framework loosely based on the MVC pattern. It
          incorporates a URL dispatcher, an object-relational mapping (ORM)
          infrastructure, and a templating system for rendering web pages.
        </p>

        <p>
          The Open Source Prospector project is built around this framework,
          making extensive use of the ORM for storing and querying data about
          tracked projects, as well as for serving web pages to the client's web
          browser.
        </p>

        <p>
          Additionally, all configuration of the Open Source Prospector project is meant
          to be done through the default web admnistrative interface provided
          by Django.
        </p>
      </dd>

      <dt><a href="http://www.postgresql.org/">PostgreSQL</a></dt>
      <dd>
        <p>
          A powerful, open source object-relational database system. It has
          more than 15 years of active development and a proven architecture
          that has earned it a strong reputation for reliability, data
          integrity, and correctness. It runs on all major operating systems,
          including Linux, UNIX (AIX, BSD, HP-UX, SGI IRIX, Mac OS X, Solaris,
          Tru64), and Windows. It is fully ACID compliant, has full support
          for foreign keys, joins, views, triggers, and stored procedures (in
          multiple languages). It includes most SQL:2008 data types, including
          INTEGER, NUMERIC, BOOLEAN, CHAR, VARCHAR, DATE, INTERVAL, and
          TIMESTAMP. It also supports storage of binary large objects,
          including pictures, sounds, or video. It has native programming
          interfaces for C/C++, Java, .Net, Perl, Python, Ruby, Tcl, ODBC,
          among others, and exceptional documentation.
        </p>
      </dd>

      <dt><a href="http://grimoirelab.github.io">Grimoire Lab</a></dt>
      <dd>
        <p>
          GrimoireLab is free, open source software for software development
          analytics. It allows you to retrieve data from many kinds of systems
          with information related to software development, and produce analysis
          and visualizations with it.
        </p>

        <p>
          GrimoireLab supports more than 20 different kinds of data sources,
          from git reposiories or GitHub projects, to issue trackers such as
          Jira or Bugzilla, including messaging systems such as IRC, Slack or
          mailing lists, or other types of systems such as StackOverflow or
          Jenkins.
       </p>

       <p>
         With the tools in the GrimoireLab toolset you can retrieve data,
         store it in databases, analyze it, and produce nice dashboards
         for interactively visualizing the resulting information.
       </p>

       <p>
         Prospector uses Perceval, a package part of Grimoire Lab, to fetch
         data from open source repositories.
       </p>
      </dd>

  </section>
{% endblock %}

wsgi/healthmeter/hmeter_frontend/templates/hmeter_frontend/all-projects.html
{% extends "hmeter_frontend/base.html" %}
{% load staticfiles %}

{% block css %}
  <link rel="stylesheet" type="text/less"
        href="{% static 'css/all-projects.less' %}" />
{% endblock css %}

{% block js %}
  <script type="text/javascript" src="{% static 'js/external-links.js' %}">
  </script>
  <script type="text/javascript" src="{% static 'js/jquery-icontains.js' %}">
  </script>
  <script type="text/javascript" src="{% static 'js/all-projects-search.js' %}">
  </script>
{% endblock js %}
{% block content %}
  <section>
    <h1>Red Hat Maintained Projects</h1>

    <p>
      This page lists all the projects that Red Hat is involved with. Please
      inform us (via the "Leave Feedback" link above) of any additions or
      changes.
    </p>

    <p>
      The information is consolidated from:
    </p>

    <ol>
      <li>
        <a href="https://fedoraproject.org/wiki/Red_Hat_contributions">
          https://fedoraproject.org/wiki/Red_Hat_contributions
        </a>
      </li>
      <li>
        <a href="http://community.redhat.com/software/">
          http://community.redhat.com/software/
        </a>
      </li>
      <li>
        <a href="http://www.sourceware.org/projects.html">
          http://www.sourceware.org/projects.html
        </a>
      </li>
      <li>
        <a href="https://developer.jboss.org/welcome">
          https://developer.jboss.org/welcome
        </a>
      </li>
    </ol>

    <p>
      Project names with a <i class="fa fa-external-link"></i> are projects that
      Prospector currently does not monitor and clicking on the project name
      will bring you to the project's website.
    </p>

    <form class="form search-form form-inline">
      <input type="search" value="Search Projects"
             class="form-control inactive" />
    </form>

    <ol>
      {% for projectinfo in projects %}
        <li>
          {% if not projectinfo.external %}
            <a href="{% url 'hmeter_frontend:project:detail' pk=projectinfo.id %}">
              {{ projectinfo.name }}
            </a>
          {% else %}
            <a href="{{ projectinfo.link }}" class="external">
              {{ projectinfo.name }}
            </a>
          {% endif %}
        </li>
      {% endfor %}
    </ol>
  </section>
{% endblock content %}

wsgi/healthmeter/hmeter_frontend/templates/hmeter_frontend/base.html
{% load compress staticfiles bootstrap activelink %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>{% block title %}Open Source Prospector{% endblock %}</title>

    <!-- CSS -->
    {% block uncompressed_css %}
      <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css"
            rel="stylesheet">
    {% endblock uncompressed_css %}
    {% compress css %}
      {# Allow this to be overridden, because this pulls in bootstrap #}
      {% block css %}
        <link rel="stylesheet" type="text/less"
              href="{% static 'css/common.less' %}" />
      {% endblock css %}
    {% endcompress %}

    <!-- JS -->
    {% block uncompressed_js %}
      <script type="text/javascript"
              src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js">
      </script>
    {% endblock uncompressed_js %}
    {% compress js %}
      <script type="text/javascript"
              src="{% static 'js/bootstrap/bootstrap.js' %}" >
      </script>
      <script type="text/javascript"
              src="{% static 'js/feedback.js' %}" >
      </script>
      {% block js %}{% endblock js %}
    {% endcompress %}

    {% block head_matter %}{% endblock %}
  </head>
  <body>
    <header class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="row">
          <a href="{% url 'hmeter_frontend:project:index' %}"
             class="navbar-brand col-sm-10">
             <img id="chaoss-logo" src="{% static 'chaoss-logo.png' %}" />
             <span>Prospector</span>
          </a>

          <button class="navbar-toggle col-sm-2 collapsed" type="button"
                  data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <nav class="collapse navbar-collapse" role="navigation">
          <ul class="nav navbar-nav">
            <li {% ifactive 'hmeter_frontend:project:index' %}
                  class="active"
                {% else %}
                  {% ifactive 'hmeter_frontend:business_units' %}
                    class="active"
                  {% else %}
                    {% ifactive 'hmeter_frontend:all_projects' %}
                      class="active"
                    {% endifactive %}
                  {% endifactive %}
                {% endifactive %}>
              <a href="#" class="dropdown-toggle"
                 data-toggle="dropdown">
                 Projects <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li {% ifactive 'hmeter_frontend:project:index' %}
                    class="active"
                    {% endifactive %}>
                  <a href="{% url 'hmeter_frontend:project:index' %}">
                    Monitored projects</a>
                </li>
                <li {% ifactive 'hmeter_frontend:business_units' %}
                    class="active"
                    {% endifactive %}>
                  <a href="{% url 'hmeter_frontend:business_units' %}">
                    By business units</a>
                </li>
                <li {% ifactive 'hmeter_frontend:all_projects' %}
                    class="active"
                  {% endifactive %}>
                  <a href="{% url 'hmeter_frontend:all_projects' %}">
                    All projects
                  </a>
                </li>
              </ul>
            </li>
            <li {% ifactive 'hmeter_frontend:about' %}
                class="active" {% endifactive %}>
              <a href="{% url 'hmeter_frontend:about' %}">About</a>
            </li>
            <li
               {% ifactive 'hmeter_frontend:contact' %}
               class="active"{% endifactive %}>
               <a href="{% url 'hmeter_frontend:contact' %}">Contact</a>
            </li>
            <li><a id="feedback-button" href="#" data-toggle="modal"
                   data-target="#feedback-modal">Leave feedback</a></li>
          </ul>

          <form class="navbar-form navbar-right" action="{% url 'admin:index' %}"
                id="admin-link">
            <button type="submit" class="btn btn-link">
              Administrator Login
            </button>
          </form>
        </nav>
      </div>
    </header>

    <div id="feedback-modal" class="modal fade">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">
              <span aria-hidden="true">&times;</span>
            </button>
            <h4>Feedback form</h4>
          </div>

          <form class="modal-body form-horizontal" id="feedback-form"
                method="post" role="form"
                action="{% url 'hmeter_frontend:feedback' %}">
                {% csrf_token %}
                {{ feedback_form|bootstrap }}
          </form>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">
              Close
            </button>

            <button type="submit" class="btn btn-primary">
              <i class="fa fa-spinner fa-spin"></i>
              Submit
            </button>
          </div>
        </div>
      </div>
    </div>

    {% block main %}
    <main role="main" class="container clearfix">
      {% block content %}
      {% endblock %}
    </main>
    {% endblock main %}
  </body>
</html>

wsgi/healthmeter/hmeter_frontend/templates/hmeter_frontend/contact.html
{% extends "hmeter_frontend/base.html" %}

{% block title %}Open Source Prospector: Contact{% endblock %}

{% block content %}
  <section>
    <h1>Contact</h1>
    <p>
      Comments and suggestions are welcome and please direct them to Harish
      Pillay &lt;{{ "hpillay@redhat.com"|urlize }}&gt;
    </p>
  </section>
{% endblock %}

wsgi/healthmeter/hmeter_frontend/templates/hmeter_frontend/migration-schedule.html
{% extends "hmeter_frontend/base.html" %}

{% block content %}
  <section>
    <h1>Migration Schedule</h1>
    <p>
      We will be migrating to a brand new OpenShift infrastructure based on
      advise from Red Hat IT. We are planning this over the weekend of August
      28th 2015. Prospector would be offline from 1200 UTC August 28th 2015. We
      anticipate the migration to take about 6 hours.
    </p>

    <p>
      If you need to access Prospector during that period, please drop us a note
      using the "Leave feedback" link above.
    </p>
  </section>
{% endblock %}