wsgi/healthmeter/hmeter_frontend/urls.py
# Copyright 2017 Red Hat, Inc.
# License: GPLv3 or any later version

from django.conf.urls import include, url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView, TemplateView

from . import views

project_urlpatterns = [
    url(r'^$', views.project.ProjectIndex.as_view(), name="index"),

    url(r'^\+problems$', views.project.ProblematicProjects.as_view(),
        name="problems"),

    url(r'^\+compare/(?P<ids>([0-9]+,)+[0-9]+)$',
        views.project.CompareProject.as_view(),
        name="compare"),

    url(r'^(?P<pk>\d+)/$', views.project.ProjectDetail.as_view(),
        name="detail"),

    url(r'^(?P<id>\d+)/commits/(?P<domain>.*)$',
        views.project.CommitDataView.as_view(),
        name="commitdata"),

    url(r'^(?P<id>\d+)/committers/(?P<domain>.*)$',
        views.project.CommitterDataView.as_view(),
        name="committerdata"),

    url(r'^(?P<id>\d+)/emails/(?P<domain>.*)$',
        views.project.MailingListDataView.as_view(),
        name="mldata"),

    url(r'^(?P<id>\d+)/emailers/(?P<domain>.*)$',
        views.project.MailingListPosterDataView.as_view(),
        name="mlposterdata"),

    url(r'^(?P<id>\d+)/bugs/(?P<domain>.*)$',
        views.project.BugDataView.as_view(),
        name="btdata"),

    url(r'^(?P<id>\d+)/bugreporters/(?P<domain>.*)$',
        views.project.BugReporterDataView.as_view(),
        name="btreporterdata"),

    url(r'^(?P<id>\d+)/blogs/$', views.project.BlogDataView.as_view(),
        name="blogdata"),

    url(r'^(?P<id>\d+)/events/$', views.project.EventDataView.as_view(),
        name="eventdata"),

    url(r'(?P<id>\d+)/metric/$', views.project.MetricDataView.as_view(),
        name="metricdata"),

    url(r'(?P<pk>\d+)/metrichistory/$',
        views.project.MetricHistoryView.as_view(),
        name="metrichistory"),
]

urlpatterns = [
    url(r'^$',
        RedirectView.as_view(
            url=reverse_lazy('hmeter_frontend:project:index'),
            permanent=True
        )),

    url(r'^about$', views.static.About.as_view(),
        name='about'),

    url(r'^contact$', views.static.Contact.as_view(),
        name='contact'),

    url(r'^feedback$', views.feedback.FeedbackView.as_view(),
        name='feedback'),

    url(r'^project/', include(project_urlpatterns,
                              namespace='project')),

    url(r'^business-units/', views.business_units.BusinessUnitIndex.as_view(),
        name='business_units'),

    url(r'^all-projects/', views.all_projects.AllProjectsView.as_view(),
        name='all_projects'),
]

wsgi/healthmeter/urls.py
# Copyright 2017 Red Hat, Inc.
# License: GPLv3 or any later version

from django.conf.urls import include, url, static
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

import django_js_reverse.views

import healthmeter.hmeter_frontend.urls
from healthmeter.views.errors import PageNotFoundView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^jsreverse/', django_js_reverse.views.urls_js,
        name='js_reverse'),
]

if settings.DEBUG:
    urlpatterns += static.static(settings.MEDIA_URL,
                                 document_root=settings.MEDIA_ROOT)

urlpatterns += [
    url(r'', include(healthmeter.hmeter_frontend.urls,
                     namespace="hmeter_frontend")),
]

handler404 = PageNotFoundView.as_view()

wsgi/healthmeter/hmeter_frontend/models.py
# Copyright 2017 Red Hat, Inc.
# License: GPLv3 or any later version

import colorful.fields
import datetime
from django.core.exceptions import ValidationError, MultipleObjectsReturned
from django.core.cache import cache
from django.core.urlresolvers import reverse
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey, TreeManyToManyField
from mptt.managers import TreeManager

from jsonfield.fields import JSONField

import hashlib
import itertools
import json
import logging

from healthmeter.participantinfo.models import *
from healthmeter.projectinfo import models as projectmodels
from healthmeter.vcsinfo import models as vcsmodels
from healthmeter.mlinfo import models as mlmodels
from healthmeter.btinfo import models as btmodels
from healthmeter.eventinfo import models as eventmodels
from healthmeter.bloginfo import models as blogmodels

from healthmeter.managers import (ProxyTreeManager, QuerySetManager,
                                  get_natural_key_manager)

from healthmeter.utils import djcached
from .utils.cache import cached_property, djcached_by_project
from .utils.containers import AttrDict
from .utils.stats import max_or_none
from .managers import ProjectQuerySet, ProjectManager
from .metrics.constants import score_to_colour


logger = logging.getLogger(__name__)


class Project(projectmodels.Project):
    objects = ProjectManager()
    QuerySet = ProjectQuerySet

    class Meta(projectmodels.Project.Meta):
        proxy = True

    def get_absolute_url(self):
        return reverse('hmeter_frontend:project:detail',
                       kwargs={'pk': self.id})

    @property
    def all_projects(self):
        return self.get_descendants(include_self=True)

    @property
    def all_releases(self):
        return projectmodels.Release.objects.filter(
            project__in=self.all_projects)

    @property
    def all_licenses(self):
        return projectmodels.License.objects.filter(
            projects__in=self.all_projects).distinct('id')

    @property
    def all_bug_trackers(self):
        return btmodels.BugNamespace.objects.filter(
            projects__in=self.all_projects)

    @property
    def all_vcs_repositories(self):
        return vcsmodels.Repository.objects.filter(
            project__in=self.all_projects)

    @property
    def all_mailing_lists(self):
        return mlmodels.MailingList.objects.filter(
            projects__in=self.all_projects)

    @property
    def all_blogs(self):
        return blogmodels.Blog.objects.filter(projects__in=self.all_projects)

    @cached_property
    @djcached_by_project('start_date', 24 * 3600)
    def smart_start_date(self):
        if self.start_date:
            return self.start_date

        try:
            return vcsmodels.Commit \
                .objects \
                .filter(
                    repository__project__in=self.all_projects
                ) \
                .aggregate(start_date=models.Min('timestamp'))['start_date'] \
                .date()
        except (KeyError, AttributeError):
            return None

    @property
    @djcached_by_project('last_updated', 24 * 3600)
    def last_updated(self):
        projects = self.all_projects

        querysets = (self.all_vcs_repositories,
                     self.all_bug_trackers,
                     self.all_mailing_lists,
                     self.all_blogs)

        last_updated_dates = (qs.aggregate(lu=models.Max('last_updated'))['lu']
                              for qs in querysets)
        return max_or_none(last_updated_dates)

    @cached_property
    @djcached_by_project('last_activity', 24 * 3600)
    def last_activity(self):
        projects = self.all_projects

        extra_args = {}

        def update_timestamp(new_timestamp):
            if new_timestamp is None:
                return

            try:
                extra_args['timestamp__gt'] = max(
                    extra_args['timestamp__gt'],
                    new_timestamp)
            except KeyError:
                extra_args['timestamp__gt'] = new_timestamp

        timestamp = vcsmodels.Commit.objects \
            .filter(repository__project__in=projects,
                    **extra_args) \
            .aggregate(timestamp=models.Max('timestamp'))['timestamp']
        update_timestamp(timestamp)

        timestamp = mlmodels.Post.objects \
            .filter(mailing_lists__projects__in=projects,
                    **extra_args) \
            .aggregate(timestamp=models.Max('timestamp'))['timestamp']
        update_timestamp(timestamp)

        timestamp = btmodels.Comment.objects \
            .filter(bug__tracker_info__projects__in=projects,
                    **extra_args) \
            .aggregate(timestamp=models.Max('timestamp'))['timestamp']
        update_timestamp(timestamp)

        timestamp = blogmodels.Post.objects \
            .filter(blog__projects__in=projects, **extra_args) \
            .aggregate(timestamp=models.Max('timestamp'))['timestamp']
        update_timestamp(timestamp)

        most_recent_date = extra_args.get('timestamp__gt', None)

        return most_recent_date

    @property
    def score(self):
        return self.get_score()

    def __gen_score_cache_key(self, start=None, end=None, **kwargs):
        epoch = datetime.datetime.utcfromtimestamp(0)

        def td2epoch(td):
            return td.days * 24 * 3600 + td.seconds

        if start:
            start = int(td2epoch(start - epoch))

        if end:
            end = int(td2epoch(end - epoch))

        return 'project:{0}:health_score:{1}:{2}'.format(self.id, start, end)

    @djcached(__gen_score_cache_key, 24 * 3600)
    def get_score(self, start=None, end=None):
        metric = Metric.objects.root_nodes()[:1][0]
        return metric.get_result(self, start, end)


class EmailDomain(EmailDomain):
    objects = QuerySetManager()

    class Meta:
        proxy = True

    class QuerySet(models.query.QuerySet):
        def with_commit_count(self):
            return self.values('domain') \
                .annotate(commit_count=models.Count('addresses__owner__'
                                                    'committer_ids__'
                                                    'commits__id',
                                                    distinct=True),
                          address_count=models.Count('addresses__id',
                                                     distinct=True)) \
                .order_by('-commit_count')

        def with_mlpost_count(self):
            return self.values('domain') \
                .annotate(mlpost_count=models.Count('addresses__owner__'
                                                    'mailing_list_'
                                                    'posts__id',
                                                    distinct=True),
                          address_count=models.Count('addresses__id',
                                                     distinct=True)) \
                .order_by('-mlpost_count')

        def with_btcomment_count(self):
            return self.values('domain') \
                .annotate(btcomment_count=models.Count('addresses__owner__'
                                                       'bug_comments__id',
                                                       distinct=True),
                          address_count=models.Count('addresses__id',
                                                     distinct=True)) \
                .order_by('-btcomment_count')

        def with_participant_count(self):
            return self.values('domain') \
                .annotate(participant_count=models.Count('addresses__owner__'
                                                         'id', distinct=True),
                          address_count=models.Count('addresses__id',
                                                     distinct=True)) \
                .order_by('-participant_count')


class MetricScoreConstants(models.Model):
    red_score = models.FloatField()
    yellow_score = models.FloatField()
    green_score = models.FloatField()

    ry_boundary = models.FloatField()
    yg_boundary = models.FloatField()

    class Meta:
        verbose_name = "Metric Score Constants"
        verbose_name_plural = "Metric Score Constants instances"

    def clean(self):
        if not (self.red_score <= self.ry_boundary <= self.yellow_score
                <= self.yg_boundary <= self.green_score):
            raise ValidationError("Green score should be highest, followed by "
                                  "yg boundary, yellow score, ry boundary, "
                                  "and red score")

    def save(self, *args, **kwargs):
        self.clean()

        return super(MetricScoreConstants, self).save(*args, **kwargs)

    def __str__(self):
        return '(red=%.2f, ry=%.2f, yellow=%.2f, yg=%.2f, green=%.2f)' % (
            self.red_score,
            self.ry_boundary,
            self.yellow_score,
            self.yg_boundary,
            self.green_score)


class MetricAlgorithm(models.Model):
    name = models.CharField(max_length=50, unique=True)
    desc = models.CharField(max_length=300)

    objects = get_natural_key_manager('name')

    def __str__(self):
        return self.name


class Metric(MPTTModel):
    parent = TreeForeignKey('self', related_name='children',
                            null=True, blank=True)
    weight = models.IntegerField()
    algorithm = models.ForeignKey(MetricAlgorithm, null=True, blank=True)
    title = models.CharField(max_length=300, blank=True)
    description = models.TextField(blank=True)
    template_name = models.CharField(max_length=50, blank=True, default='')
    sibling_order = models.IntegerField(default=0, blank=True)
    colour = colorful.fields.RGBColorField(blank=True)

    time_based = models.BooleanField(default=True)

    class MPTTMeta:

wsgi/healthmeter/hmeter_frontend/forms.py
# Copyright 2017 Red Hat, Inc.
# License: GPLv3 or any later version

from django import forms


class FeedbackForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    subject = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

wsgi/healthmeter/hmeter_frontend/views/business_units.py
# Copyright 2017 Red Hat, Inc.
# License: GPLv3 or any later version

from django.views.generic import TemplateView
import itertools

from healthmeter.utils import ProxyObject
from healthmeter.hmeter_frontend.models import Project, Metric
from healthmeter.projectinfo.models import BusinessUnit


class BusinessUnitIndex(TemplateView):
    template_name = 'hmeter_frontend/business-units.html'

    def get_context_data(self, **kwargs):
        data = super(BusinessUnitIndex, self).get_context_data(**kwargs)
        business_units = BusinessUnit.objects.prefetch_related('products')
        projects = Project.objects.filter(parent__isnull=True) \
                                  .order_by('business_unit') \
                                  .prefetch_dates() \
                                  .with_l1_scores()

        bu_index = dict(
            (buid, list(projs))
            for buid, projs in
            itertools.groupby(projects, lambda p: p.business_unit_id))

        data['descriptions'] = dict((project.id, project.description)
                                    for project in projects)

        def get_products(bu):
            # sort locally because of prefetch
            for product in sorted(bu.products.all(), key=lambda p: p.name):
                if product.name == 'JBoss BRMS':
                    yield ProxyObject(product,
                                      projects=bu_index.get(bu.id, None))
                else:
                    yield product

        data['business_units'] = [
            ProxyObject(bu,
                        root_projects=bu_index.get(bu.id, None),
                        products=get_products(bu))
            for bu in business_units
        ]
        data['unassociated_projects'] = bu_index[None]

        data['l1_metrics'] = Metric.objects.filter(level=1).order_by('lft')

        return data

wsgi/healthmeter/hmeter_frontend/views/feedback.py
# Copyright 2017 Red Hat, Inc.
# License: GPLv3 or any later version

from django.conf import settings
from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseBadRequest
from django.views.generic import View
from django.views.decorators.csrf import csrf_exempt

from healthmeter.views.generic import JsonView
from healthmeter.hmeter_frontend.forms import FeedbackForm
import json


class FeedbackView(View):
    @classmethod
    def as_view(cls, *args, **kwargs):
        return csrf_exempt(super().as_view(*args, **kwargs))

    @staticmethod
    def format_email(name, email):
        return '{0} <{1}>'.format(name, email)

    def post(self, request, *args, **kwargs):
        form = FeedbackForm(request.POST)

        if not form.is_valid():
            respdata = {
                'status': 'fail',
                'errors': form.errors
            }
            responsecls = HttpResponseBadRequest

        else:
            respdata = {
                'status': 'ok',
                'errors': {}
            }
            responsecls = HttpResponse
            recipients = [self.format_email(name, email)
                          for name, email in settings.MANAGERS]

            message = '{0}\n-- \nSent from: {1}\n'.format(
                form.cleaned_data['message'],
                request.META['HTTP_REFERER'])

            send_mail(subject='[OSP feedback] ' + form.cleaned_data['subject'],
                      message=message,
                      from_email=self.format_email(
                          form.cleaned_data['name'],
                          form.cleaned_data['email']),
                      recipient_list=recipients)

        return responsecls(json.dumps(respdata),
                           content_type='application/json')

wsgi/healthmeter/hmeter_frontend/views/static.py
# Copyright 2017 Red Hat, Inc.
# License: GPLv3 or any later version

from django.views.generic import TemplateView


class About(TemplateView):
    template_name = 'hmeter_frontend/about.html'


class Contact(TemplateView):
    template_name = 'hmeter_frontend/contact.html'


class MigrationSchedule(TemplateView):
    template_name = 'hmeter_frontend/migration-schedule.html'

wsgi/healthmeter/hmeter_frontend/templates/hmeter_frontend/project/compare.html
{% extends "hmeter_frontend/base.html" %}
{% load metrics divby %}

{% block title %}Open Source Prospector: Compare Projects{% endblock %}

{% block head_matter %}
  <link rel="stylesheet" type="text/css"
        href="{% static 'css/project-compare.css' %}" />
  <script type="text/javascript"
          src="{% static 'js/jquery-sortable.js' %}">
  </script>
  <script type="text/javascript" src="{% static 'js/jquery.flot.min.js' %}">
  </script>
  <script type="text/javascript"
          src="{% static 'js/jquery.flot.time.min.js' %}">
  </script>
  <script type="text/javascript"
          src="{% static 'js/project/health-score-utils.js' %}">
  </script>
  <script type="text/javascript"
          src="{% static 'js/project/compare/colourize.js' %}">
  </script>
  <script type="text/javascript"
          src="{% static 'js/project/compare/draggable-headers.js' %}">
  </script>
  <script type="text/javascript"
          src="{% static 'js/project/compare/scorebars.js' %}">
  </script>
  <script type="text/javascript"
          src="{% static 'js/project/compare/expandable-metrics.js' %}">
  </script>


  {% with projlen=projects|length %}
    <style type="text/css">
      col.project {
          width: {{ 60|divby:projlen }}%;
      }
    </style>
  {% endwith %}
{% endblock %}

{% block content %}
<section>
  <h1>Compare Projects</h1>

  <div class="horiz-scrollable">
    <table id="project-comparison">
      <colgroup>
        <col class="metric" />
      </colgroup>

      <colgroup span="{{ projects|length }}" class="project-columns">
        {% for i in projects %}
          <col class="project" />
        {% endfor %}
      </colgroup>

      <thead>
        <tr>
          <th></th> <!-- Sink the metric column -->
          {% for proj in projects %}
            <th data-project-id="{{ proj.id }}" class="project">
              <a href="{% url 'hmeter_frontend:project:detail' pk=proj.id %}">
                {{ proj.name }}
              </a>
            </th>
          {% endfor %}
        </tr>
      </thead>

      <tbody class="metric-scorebars">
        {% for entry in l1_score_breakdown %}
          <tr>
            <td class="metric"
                {% if entry.colour %}
                  style="color: {{ entry.colour }}"
                {% endif %}
                >
                {{ entry.title }}
            </td>

            {% for data in entry.datalist %}
              <td class="project">
                <div class="health-scorebar"
                     data-health-score="{{ data.score }}">
                </div>
              </td>
            {% endfor %}
          </tr>
        {% endfor %}
      </tbody>

      <tbody class="metric-rows">
        {% for entry in score_breakdown %}
          <tr data-level="{{ entry.level }}" data-metric-id="{{ entry.id }}"
              data-metric-timebased="{{ entry.time_based }}">
            <td class="metric"
                {% if entry.colour %}
                  style="color: {{ entry.colour }}"
                {% endif %}
                >{{ entry.title }}
            </td>

            {% for data in entry.datalist %}
              {% if entry.has_children %}
                {# children are present, so don't show N/A score #}
                <td class="project"></td>

              {% else %}
                <td data-health-score="{{ data.score }}"
                    class="project">
                  {{ data.raw_value|format_score }}{{ data.unit }}
                </td>
              {% endif %}
            {% endfor %}
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</section>
{% endblock %}

wsgi/healthmeter/hmeter_frontend/templates/hmeter_frontend/project/index.html
{% extends "hmeter_frontend/base.html" %}

{% load staticfiles %}
{% load metrics jsonify %}

{% block title %}Open Source Prospector: Project Listing{% endblock %}

{% block css %}
  <link rel="stylesheet" type="text/less"
        href="{% static 'css/project-index.less' %}" />
{% endblock css %}

{% block uncompressed_js %}
  {{ block.super }}
  <script type="text/javascript"
          src="{% url 'js_reverse' %}">
  </script>
  <script type="text/javascript">
    var descriptions = {{ descriptions|jsonify }};
  </script>
{% endblock uncompressed_js %}
{% block js %}
  {{ block.super }}
  <script type="text/javascript"
          src="{% static 'js/jquery.tablesorter/js/jquery.tablesorter.js' %}">
  </script>
  <script type="text/javascript"
          src="{% static 'js/jquery.tablesorter/js/jquery.tablesorter.widgets.js' %}">
  </script>
  <script type="text/javascript"
          src="{% static 'js/jquery.tablesorter/beta-testing/pager-custom-controls.js' %}">
  </script>
  <script type="text/javascript"
          src="{% static 'js/jquery.tablesorter/addons/pager/jquery.tablesorter.pager.js' %}">
  </script>
  <script type="text/javascript"
          src="{% static 'js/jquery.tablesorter/js/parsers/parser-date.js' %}">
  </script>
  <script type="text/javascript"
          src="{% static 'js/derived.js' %}">
  </script>
  <script type="text/javascript"
          src="{% static 'js/project/health-score-utils.js' %}">
  </script>
  <script type="text/javascript"
          src="{% static 'js/project/index/health-scores.js' %}">
  </script>
  <script type="text/javascript"
          src="{% static 'js/project/index/tablesorter.js' %}">
  </script>
  <script type="text/javascript"
          src="{% static 'js/project/index/compare.js' %}">
  </script>
{% endblock js%}

{% block content %}
<section>
  <h1>Monitored Projects</h1>
  <a href="{% url 'hmeter_frontend:business_units' %}" id="business-units-link">
    Alternate view of projects based on Business Units </a>

    {% include "hmeter_frontend/project/fragments/project-listing-table.html" %}
</section>
{% endblock%}

wsgi/healthmeter/hmeter_frontend/templates/hmeter_frontend/project/metric-history.html
{% extends "hmeter_frontend/base.html" %}

{% block title %}
  Open Source Prospector: {{ project.name }} score history
{% endblock title %}

{% block head_matter %}
  <link type="text/css" rel="stylesheet"
        href="{% static 'css/project-compare.css' %}" />
{% endblock head_matter %}

{% block content %}
  <section>
    <h1>Score history for {{ project.name }}</h1>

    <div class="horiz-scrollable">
      <table id="project-metric-scores">
        <colgroup>
          <col class="metric" />
          {% for date in dates %}
            <col class="score" />
          {% endfor %}
        </colgroup>

        <thead>
          <tr>
            <th></th> <!-- Sink the metric column -->
            {% for date in dates %}
              <th>{{ date|date:"DATE_FORMAT" }}</th>
            {% endfor %}
          </tr>
        </thead>

        <tbody>
          {% for metric in metricdata %}
            <tr class="level{{ metric.level }}">
              <td class="metric">{{ metric.title }}</td>
              {% for line in metric.datalist %}
                <td>raw={{ line.raw_value }}, score={{ line.score }}</td>
              {% endfor %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

  </section>
{% endblock content %}

wsgi/healthmeter/hmeter_frontend/templates/hmeter_frontend/project/problems.html
{% extends "hmeter_frontend/base.html" %}

{% block title %}Open Source Prospector: Problems{% endblock %}

{% block head_matter %}
  <link rel="stylesheet" type="text/css"
        href="{% static 'css/project-problems.css' %}" />
{% endblock head_matter %}

{% block content %}
  <section>
    <h1>Projects with Problems</h1>
    <ul id="project-problems">
      {% for project, problems in project_problems %}
        <li id="project-{{ project.id }}">
          <a href="{% url 'hmeter_frontend:project:detail' pk=project.id %}">
            {{ project.name }}
          </a>

          <ul>
            {% for problem in problems %}
              <li>{{ problem }}</li>
            {% endfor %}
          </ul>
        </li>
      {% endfor %}
    </ul>
  </section>
{% endblock content %}